# Generated by Django 2.2.3 on 2019-07-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('url', models.URLField(blank=True, null=True)),
                ('shop', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=1)),
            ],
        ),
    ]
